apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubevirt-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kubevirt-operator
  template:
    metadata:
      labels:
        name: kubevirt-operator
    spec:
      containers:
        - name: kubevirt-operator
          image: docker.io/rthallisey/kubevirt-operator
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - kubevirt-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OPERATOR_NAME
              value: "kubevirt-operator"
